### ISSUE TITLE
一个构造是无效的

### ISSUE THREAD

**Issue by HYWZ36** [feihong-cs/jre8u20_gadget#1]
我测试后发现，TestCase2.java中的弹窗其实是构造时触发的，不是反序列化时触发的

**Comment by HYWZ36** [comment]
我是在7u17上操作的

**Comment by feihong-cs** [comment]
你说的问题是对的，这个是我大意了，但是 8u20 的 gadget 测试是正常的。这个项目时间有点久了，暂时没有啥头绪，等将来有空的时候也许我会找下原因并更新下，谢谢提醒

**Comment by feihong-cs** [comment]
今天抽空看了下，这个问题是 Payload 类构造的不正确导致的，目前已更新，现在没问题了
